### ISSUE TITLE
`require': cannot load such file -- /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-google-cloud-0.5.3/lib/fluent/plugin/out_google_cloud (LoadError)

### ISSUE THREAD

**Issue by pnovotnak** [GoogleCloudPlatform/fluent-plugin-google-cloud#105]
At Cyrus Biotechnology we use fluentd running as a Kubernetes daemonset to relay logs from workers without public IP addresses to cloud logging. As of very recently we were using the fluent/fluentd:latest container as a base; 

```dockerfile
FROM fluent/fluentd:latest
#
# Fluentd with custom configuration
#
MAINTAINER Peter Novotnak <peter@cyrusbio.com>

USER root

RUN apk update \
  && apk add ruby-dev build-base

USER fluent

WORKDIR /home/fluent

ENV PATH /home/fluent/.gem/ruby/2.2.0/bin:$PATH

RUN gem install fluent-plugin-google-cloud

ADD fluent.conf /fluentd/etc/fluent.conf

# 514 is privileged
EXPOSE 5140
CMD fluentd -vvv -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```

But the containers built that way have started throwing the following;

```
/home/fluent/.gem/ruby/2.3.0/gems/grpc-1.0.1-x86_64-linux/src/ruby/lib/grpc/grpc.rb:35:in `require_relative': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/fluent/.gem/ruby/2.3.0/gems/grpc-1.0.1-x86_64-linux/src/ruby/lib/grpc/2.3/grpc_c.so) - /home/fluent/.gem/ruby/2.3.0/gems/grpc-1.0.1-x86_64-linux/src/ruby/lib/grpc/2.3/grpc_c.so (LoadError)
	from /home/fluent/.gem/ruby/2.3.0/gems/grpc-1.0.1-x86_64-linux/src/ruby/lib/grpc/grpc.rb:35:in `<top (required)>'
	from /home/fluent/.gem/ruby/2.3.0/gems/grpc-1.0.1-x86_64-linux/src/ruby/lib/grpc/errors.rb:30:in `require_relative'
	from /home/fluent/.gem/ruby/2.3.0/gems/grpc-1.0.1-x86_64-linux/src/ruby/lib/grpc/errors.rb:30:in `<top (required)>'
	from /home/fluent/.gem/ruby/2.3.0/gems/grpc-1.0.1-x86_64-linux/src/ruby/lib/grpc.rb:32:in `require_relative'
	from /home/fluent/.gem/ruby/2.3.0/gems/grpc-1.0.1-x86_64-linux/src/ruby/lib/grpc.rb:32:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-google-cloud-0.5.3/lib/fluent/plugin/out_google_cloud.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/plugin.rb:172:in `block in try_load_plugin'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/plugin.rb:170:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/plugin.rb:170:in `try_load_plugin'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/plugin.rb:130:in `new_impl'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/plugin.rb:59:in `new_output'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:131:in `add_match'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:64:in `block in configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:57:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:57:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/root_agent.rb:86:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/engine.rb:129:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/engine.rb:103:in `run_configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:489:in `run_configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:160:in `block in start'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:366:in `main_process'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:339:in `block in supervise'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:338:in `fork'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:338:in `supervise'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:156:in `start'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/bin/fluentd:5:in `<top (required)>'
	from /usr/bin/fluentd:23:in `load'
	from /usr/bin/fluentd:23:in `<main>'
```

Great! Looks like a musl / glibc issue, I can solve this. So, I switched over to a debian base image, but now I get new issues. I tried switching from fluentd to td-agent, then, as a last resort, I switched to the google installer (`https://storage.googleapis.com/signals-agents/logging/google-fluentd-install.sh | sh`) to no effect. I'm stuck here;

```
/opt/google-fluentd/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-google-cloud-0.5.3/lib/fluent/plugin/out_google_cloud (LoadError)
	from /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/registry.rb:94:in `block in search'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/registry.rb:92:in `each'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/registry.rb:92:in `search'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/registry.rb:43:in `lookup'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/plugin.rb:146:in `new_impl'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/plugin.rb:104:in `new_output'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/agent.rb:125:in `add_match'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/agent.rb:70:in `block in configure'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/agent.rb:63:in `each'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/agent.rb:63:in `configure'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/root_agent.rb:86:in `configure'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/engine.rb:119:in `configure'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/engine.rb:93:in `run_configure'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:693:in `run_configure'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:453:in `block in run_worker'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:626:in `call'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:626:in `main_process'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:449:in `run_worker'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/command/fluentd.rb:288:in `<top (required)>'
	from /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/bin/fluentd:5:in `<top (required)>'
	from /opt/google-fluentd/embedded/bin/fluentd:23:in `load'
	from /opt/google-fluentd/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/google-fluentd:7:in `load'
	from /usr/sbin/google-fluentd:7:in `<main>'
```

Here's a dockerfile that can be used to repro;

```dockerfile
FROM debian:jessie-slim
MAINTAINER Peter Novotnak <peter@cyrusbio.com>
LABEL Description="Fluentd agent docker image" Vendor="Cyrus Biotechnology" Version="1.2"

# Do not split this into multiple RUN!
# Docker creates a layer for every RUN-Statement
# therefore an 'apk delete build*' has no effect
RUN apt-get update \
  && apt-get install -qy curl \
  && curl -L https://storage.googleapis.com/signals-agents/logging/google-fluentd-install.sh | bash \
  && service google-fluentd stop \
  && apt-get remove --purge -qy curl build-essential ruby-dev \
  && apt-get autoremove --purge -qy \
  && apt-get clean \
  && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

RUN adduser \
  --disabled-password \
  --uid 1000 \
  --gecos 'fluentd' \
  --home /home/fluent \
    fluent

# for log storage (maybe shared with host)
RUN mkdir -p /fluentd/log
# configuration/plugins path (default: copied from .)
RUN mkdir -p /fluentd/etc /fluentd/plugins

RUN chown -R fluent:fluent /fluentd

ENV PATH /home/fluent/.gem/ruby/2.1.0/bin:$PATH
ENV GEM_PATH /home/fluent/.gem/ruby/2.1.0:/var/lib/gems/2.1.0/gems:$GEM_PATH

ENV FLUENTD_OPT=""
ENV FLUENTD_CONF="fluent.conf"

COPY fluent.conf /fluentd/etc/

EXPOSE 24224 5140

USER fluent
WORKDIR /home/fluent
CMD google-fluentd -vvv -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```

And the `fluent.conf` currently in use;

```fluent.conf
<source>
  @type ******
  *** censored ***
  tag workers
</source>

<match workers.**>
  type google_cloud
  # Set the chunk limit conservatively to avoid exceeding the GCL limit
  # of 2MB per write request.
  buffer_chunk_limit 512K
  # Cap buffer memory usage to 512KB/chunk * 128 chunks = 65 MB
  buffer_queue_limit 128
  flush_interval 5s
  # Never wait longer than 5 minutes between retries.
  max_retry_wait 300
  # Disable the limit on the number of retries (retry forever).
  disable_retry_limit
</match>
```

Am I doing something wrong?

**Comment by kumudt** [comment]
Facing the exact problem. Is there any solution for this yet??

**Comment by igorpeshansky** [comment]
Is this still happening with the latest plugin version ([0.6.1](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/releases/tag/v0.6.1))? If so, please include the repro steps on a vanilla VM and we'll take a look.

**Comment by vazhnov** [comment]
I tried to use "fluent/fluentd:v0.14.21" and "fluent/fluentd:v0.12.40", got the same error.

Dockerfile:
```Dockerfile
FROM fluent/fluentd:v0.14.21
RUN apk add --update --virtual .build-deps sudo build-base ruby-dev libc6-compat \
 && sudo gem install fluent-plugin-google-cloud \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem
EXPOSE 24224
```

`fluent.conf`:

```conf
<source>
@type forward
default port
port 24224
bind 0.0.0.0
</source>

<match **>
  type google_cloud
</match>
```

Start command:

```bash
docker run -p 24224:24224 -p 24224:24224/udp -v /mnt/tmp/fluentd/etc:/fluentd/etc fluent-plugin-google-cloud:v0.14.21-4
```

Error:

```text
2017-10-09 12:49:25 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2017-10-09 12:49:25 +0000 [warn]: 'type' is deprecated parameter name. use '@type' instead.
/usr/lib/ruby/gems/2.3.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/grpc.rb:35:in `require_relative': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/lib/ruby/gems/2.3.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/2.3/grpc_c.so) - /usr/lib/ruby/gems/2.3.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/2.3/grpc_c.so (LoadError)
	from /usr/lib/ruby/gems/2.3.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/grpc.rb:35:in `<top (required)>'
	from /usr/lib/ruby/gems/2.3.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/errors.rb:30:in `require_relative'
	from /usr/lib/ruby/gems/2.3.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/errors.rb:30:in `<top (required)>'
	from /usr/lib/ruby/gems/2.3.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc.rb:32:in `require_relative'
	from /usr/lib/ruby/gems/2.3.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc.rb:32:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-google-cloud-0.6.8/lib/fluent/plugin/out_google_cloud.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:102:in `block in search'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:99:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:99:in `search'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:44:in `lookup'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin.rb:146:in `new_impl'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin.rb:104:in `new_output'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:128:in `add_match'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:72:in `block in configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:64:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:64:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/root_agent.rb:112:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/engine.rb:131:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/engine.rb:96:in `run_configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:770:in `run_configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:553:in `dry_run'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:571:in `supervise'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:476:in `run_supervisor'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/bin/fluentd:5:in `<top (required)>'
	from /usr/bin/fluentd:22:in `load'
	from /usr/bin/fluentd:22:in `<main>'
```

**Comment by qingling128** [comment]
@vazhnov - Hi, that looks like a gRPC issue. We've noticed in the past that certain gRPC versions broke our stuff on specific platforms.

BTW our team have recently built a docker container image for the Logging Agent. We have not yet started to officially support the image yet (it's on our roadmap). Do you mind trying this instead?

```
$ cat Dockerfile
FROM ubuntu:xenial
RUN apt-get update \
    && apt-get install -y \
        curl \
        lsb-release \
    && curl -sS https://dl.google.com/cloudagents/install-logging-agent.sh | bash \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*
CMD /usr/sbin/google-fluentd
```

```
$ sudo docker build . -t issue105-test
...
```

```
$ docker run -it issue105-test bash
root@b5cf6ac21b29:/# /opt/google-fluentd/embedded/bin/gem list | grep fluent-plugin-google-cloud
fluent-plugin-google-cloud (0.6.8)
root@b5cf6ac21b29:/# tail /var/log/google-fluentd/google-fluentd.log | grep running
2017-10-11 15:59:31 +0000 [info]: #0 fluentd worker is now running worker=0
```

**Comment by vazhnov** [comment]
@qingling128 , thanks, I've created good image by this `Dockerfile`:

```Dockerfile
FROM ubuntu:16.04
COPY application_default_credentials.json /etc/google/auth/
ENV DEBIAN_FRONTEND noninteractive
# Keeps unneeded configs from being installed along with fluentd.
ENV DO_NOT_INSTALL_CATCH_ALL_CONFIG true
RUN set -x \
 && apt-get -qq update; apt-get --no-install-recommends -y install ca-certificates curl lsb-release netcat-openbsd net-tools \
 && curl -sSO https://dl.google.com/cloudagents/install-logging-agent.sh \
 && bash install-logging-agent.sh \
 && /usr/sbin/google-fluentd-gem update fluent-plugin-google-cloud \
 && rm install-logging-agent.sh \
 && apt-get clean \
 && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* \
    /opt/google-fluentd/embedded/share/doc \
    /opt/google-fluentd/embedded/share/gtk-doc \
    /opt/google-fluentd/embedded/lib/postgresql \
    /opt/google-fluentd/embedded/bin/postgres \
    /opt/google-fluentd/embedded/share/postgresql
COPY fluent.conf /etc/google-fluentd/google-fluentd.conf
CMD /usr/sbin/google-fluentd
EXPOSE 24224 24231
```
But docker image size too big: 414MB.

**Comment by qingling128** [comment]
@vazhnov - Yeah... because of the gem dependencies and also a version of embedded Ruby in it. 

Glad to hear the image works! I'm gonna close this ticket then.

**Comment by igorpeshansky** [comment]
FWIW, we'll work on reducing the image size separately.
