### ISSUE TITLE
Export to Stackdriver does not work: undefined method `upcase' for nil:NilClass

### ISSUE THREAD

**Issue by kop** [GoogleCloudPlatform/fluent-plugin-google-cloud#169]
On GKE, after upgrading to K8S version 1.7.6 (and 1.7.8) logging is stopped to work for my company cluster almost completely.

The following error can be found in `fluentd-gcp` containers:

```
2017-10-16 13:12:46 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2017-10-16 13:18:48 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-10-16 13:18:49 +0000 error_class="NoMethodError" error="undefined method `upcase' for nil:NilClass" plugin_id="object:3fbb9e6510a0"
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-google-cloud-0.6.8.pre.1/lib/fluent/plugin/out_google_cloud.rb:1420:in `parse_severity'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-google-cloud-0.6.8.pre.1/lib/fluent/plugin/out_google_cloud.rb:1327:in `compute_severity'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-google-cloud-0.6.8.pre.1/lib/fluent/plugin/out_google_cloud.rb:496:in `block (2 levels) in write'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-google-cloud-0.6.8.pre.1/lib/fluent/plugin/out_google_cloud.rb:461:in `each'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-google-cloud-0.6.8.pre.1/lib/fluent/plugin/out_google_cloud.rb:461:in `block in write'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-google-cloud-0.6.8.pre.1/lib/fluent/plugin/out_google_cloud.rb:455:in `each'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-google-cloud-0.6.8.pre.1/lib/fluent/plugin/out_google_cloud.rb:455:in `write'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/buffer.rb:333:in `pop'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/output.rb:342:in `try_flush'
  2017-10-16 13:18:48 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/output.rb:149:in `run'
```

I've tried switching to different versions of `fluentd-gcp`, however, this problem is happening on every version of the image with version 0.6.X of the plugin.

We are writing JSON logs according to Stackdriver LogEntry format and it was working just fine for a long time.

It also worth mentioning, that we have some node pools that do not have apps that are logging in JSON format and logging is working fine for them.

**Comment by igorpeshansky** [comment]
Can you post a (sanitized) example log entry? I'm mostly interested in the top-level JSON fields.

**Comment by kop** [comment]
@igorpeshansky Thank you for a response.

I've solved this problem already, so can't find an example log entry now, however, can share some details.

The problem was in logger of one of our applications. There was a bug that caused `severity` fields to have `null` value. The plugin was not able to parse such entries and raised exceptions. Because of those exceptions, all logs from nodes where we had a copy of faulty application were not reaching Stackdriver anymore.

**Comment by igorpeshansky** [comment]
Thanks for the report. We're going to make the plugin more robust to handle such situations.
