### ISSUE TITLE
 Failed to start LSB: data collector for Treasure Data. 

### ISSUE THREAD

**Issue by chetan-happyness** [GoogleCloudPlatform/fluent-plugin-google-cloud#359]
Command to install logging agent failed   - sudo bash install-logging-agent.sh

```
$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

```
ubuntu@ip-172-31-45-41:~$ systemctl status google-fluentd.service

● google-fluentd.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/init.d/google-fluentd; generated)

   Active: failed (Result: exit-code) since Mon 2019-11-25 06:43:59 UTC; 12s ago
     Docs: man:systemd-sysv-generator(8)

  Process: 6986 ExecStart=/etc/init.d/google-fluentd start (code=exited, status=1/FAILURE)

Nov 25 06:43:59 ip-172-31-45-41 google-fluentd[6986]:         from /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Nov 25 06:43:59 ip-172-31-45-41 google-fluentd[6986]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/bin/fluentd:8:in `<top (required)>'
Nov 25 06:43:59 ip-172-31-45-41 google-fluentd[6986]:         from /opt/google-fluentd/embedded/bin/fluentd:23:in `load'
Nov 25 06:43:59 ip-172-31-45-41 google-fluentd[6986]:         from /opt/google-fluentd/embedded/bin/fluentd:23:in `<top (required)>'
Nov 25 06:43:59 ip-172-31-45-41 google-fluentd[6986]:         from /usr/sbin/google-fluentd:7:in `load'
Nov 25 06:43:59 ip-172-31-45-41 google-fluentd[6986]:         from /usr/sbin/google-fluentd:7:in `<main>'
Nov 25 06:43:59 ip-172-31-45-41 google-fluentd[6986]:  * google-fluentd
Nov 25 06:43:59 ip-172-31-45-41 systemd[1]: google-fluentd.service: Control process exited, code=exited status=1
Nov 25 06:43:59 ip-172-31-45-41 systemd[1]: google-fluentd.service: Failed with result 'exit-code'.
Nov 25 06:43:59 ip-172-31-45-41 systemd[1]: Failed to start LSB: data collector for Treasure Data
```

**Comment by igorpeshansky** [comment]
Looks like some gem failed to load, but, unfortunately, the log you quoted has cut off the actual exception message. Can you please look at the output of `journalctl -xe` right after the failure? Also, is this on a GCE VM?

**Comment by chetan-happyness** [comment]
I m using aws ec2 ubuntu instance 

```ubuntu@ip-172-31-45-41:~$ journalctl -xe
-- 
-- Kernel start-up required 4393716 microseconds.
-- 
-- Initial RAM disk start-up required INITRD_USEC microseconds.
-- 
-- Userspace start-up required 23833212 microseconds.
Nov 26 10:54:38 ip-172-31-45-41 systemd-timesyncd[564]: Synchronized to time server 91.189.89.198:123 (ntp.ubuntu.com).
Nov 26 10:55:01 ip-172-31-45-41 CRON[2375]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 26 10:55:01 ip-172-31-45-41 CRON[2381]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 26 10:55:01 ip-172-31-45-41 CRON[2375]: pam_unix(cron:session): session closed for user root
Nov 26 10:55:24 ip-172-31-45-41 sshd[2384]: Accepted publickey for ubuntu from 14.143.24.106 port 48280 ssh2: RSA SHA256:cYXewJV67FDP4yWJaVH2E290vgzWw8TT127pnvqmdvw
Nov 26 10:55:24 ip-172-31-45-41 sshd[2384]: pam_unix(sshd:session): session opened for user ubuntu by (uid=0)
Nov 26 10:55:24 ip-172-31-45-41 systemd[1]: Created slice User Slice of ubuntu.
-- Subject: Unit user-1000.slice has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit user-1000.slice has finished starting up.
-- 
-- The start-up result is RESULT.
Nov 26 10:55:24 ip-172-31-45-41 systemd[1]: Starting User Manager for UID 1000...
-- Subject: Unit user@1000.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit user@1000.service has begun starting up.
Nov 26 10:55:24 ip-172-31-45-41 systemd[1]: Started Session 2 of user ubuntu.
-- Subject: Unit session-2.scope has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit session-2.scope has finished starting up.
-- 
-- The start-up result is RESULT.
Nov 26 10:55:24 ip-172-31-45-41 systemd-logind[971]: New session 2 of user ubuntu.
-- Subject: A new session 2 has been created for user ubuntu
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A new session with the ID 2 has been created for the user ubuntu.
-- 
-- The leading process of the session is 2384.
Nov 26 10:55:24 ip-172-31-45-41 systemd[2394]: pam_unix(systemd-user:session): session opened for user ubuntu by (uid=0)
Nov 26 10:55:24 ip-172-31-45-41 systemd[1]: Started User Manager for UID 1000.
-- Subject: Unit user@1000.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit user@1000.service has finished starting up.
-- 
-- The start-up result is RESULT.```

**Comment by igorpeshansky** [comment]
This stack trace is cut off horizontally, plus it doesn't quite look like the same error (and the google-fluentd pid is different). This particular one is a failure to load the service account credentials; see our [troubleshooting documentation](https://cloud.google.com/logging/docs/agent/troubleshooting#verify-key).

If you manage to reproduce the original error (e.g., by uninstalling and attempting to reinstall the agent), please provide the full log snippet starting at the `-- Unit google-fluentd.service has begun starting up.` message, without a horizontal cutoff.

**Comment by medb** [comment]
We are seeing the same issue on Debian 9 VMs:
```
-- Logs begin at Mon 2019-11-25 23:56:36 UTC, end at Tue 2019-11-26 15:45:55 UTC. --
Nov 25 23:56:52 test-vm systemd[1]: Starting LSB: data collector for Treasure Data...
Nov 25 23:57:00 test-vm google-fluentd[2908]: Starting google-fluentd 1.6.25: /etc/google-fluentd/plugin/monitoring.rb:19:in `counter': undefined local variable or method `_undefined' for #<Monitoring::BaseMonitoringRegistry:0x00007f3b14d0a830> (NameError)
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /etc/google-fluentd/plugin/out_google_cloud.rb:491:in `configure'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/plugin.rb:164:in `configure'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/agent.rb:130:in `add_match'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/agent.rb:72:in `block in configure'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/agent.rb:64:in `each'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/agent.rb:64:in `configure'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/root_agent.rb:150:in `configure'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/engine.rb:131:in `configure'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/engine.rb:96:in `run_configure'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/supervisor.rb:804:in `run_configure'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/supervisor.rb:581:in `dry_run'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/supervisor.rb:599:in `supervise'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/supervisor.rb:504:in `run_supervisor'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/command/fluentd.rb:314:in `<top (required)>'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/bin/fluentd:8:in `<top (required)>'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/bin/fluentd:23:in `load'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /opt/google-fluentd/embedded/bin/fluentd:23:in `<top (required)>'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /usr/sbin/google-fluentd:7:in `load'
Nov 25 23:57:00 test-vm google-fluentd[2908]:         from /usr/sbin/google-fluentd:7:in `<main>'
Nov 25 23:57:00 test-vm google-fluentd[2908]: google-fluentd ... failed!
Nov 25 23:57:00 test-vm systemd[1]: google-fluentd.service: Control process exited, code=exited status=1
Nov 25 23:57:00 test-vm systemd[1]: Failed to start LSB: data collector for Treasure Data.
Nov 25 23:57:00 test-vm systemd[1]: google-fluentd.service: Unit entered failed state.
Nov 25 23:57:00 test-vm systemd[1]: google-fluentd.service: Failed with result 'exit-code'.
```

**Comment by igorpeshansky** [comment]
@medb Yes, please. There are many reasons why the agent might fail to start, and it's best to keep track of separate investigations in separate issues. If we discover that they are failing for the same reasons, we can always dupe them to one another.

**Comment by chetan-happyness** [comment]
output of  journalctl -xe

``` sudo journalctl -xe
Nov 29 09:54:08 ip-172-31-39-186 systemd[1]: google-fluentd.service: Control process exited, code=exited status=1
Nov 29 09:54:08 ip-172-31-39-186 google-fluentd[20550]:  * google-fluentd
Nov 29 09:54:08 ip-172-31-39-186 systemd[1]: google-fluentd.service: Failed with result 'exit-code'.
Nov 29 09:54:08 ip-172-31-39-186 systemd[1]: Failed to start LSB: data collector for Treasure Data.
-- Subject: Unit google-fluentd.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit google-fluentd.service has failed.
-- 
-- The result is RESULT.
Nov 29 09:54:09 ip-172-31-39-186 systemd[1]: Starting LSB: data collector for Treasure Data...
-- Subject: Unit google-fluentd.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit google-fluentd.service has begun starting up.
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]: Starting google-fluentd 1.6.25: /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/googleauth-0.9.0/lib/googleauth/application_default.rb:74:in `get_application_default': Could not load the default credentials. Br
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]: https://developers.google.com/accounts/docs/application-default-credentials
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]: for more information
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluent-plugin-google-cloud-0.7.26/lib/fluent/plugin/out_google_cloud.rb:1616:in `project_id'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluent-plugin-google-cloud-0.7.26/lib/fluent/plugin/out_google_cloud.rb:1175:in `set_project_id'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluent-plugin-google-cloud-0.7.26/lib/fluent/plugin/out_google_cloud.rb:1154:in `set_required_metadata_variables'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluent-plugin-google-cloud-0.7.26/lib/fluent/plugin/out_google_cloud.rb:541:in `configure'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/plugin.rb:164:in `configure'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/agent.rb:130:in `add_match'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/agent.rb:72:in `block in configure'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/agent.rb:64:in `each'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/agent.rb:64:in `configure'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/root_agent.rb:150:in `configure'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/engine.rb:131:in `configure'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/engine.rb:96:in `run_configure'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/supervisor.rb:804:in `run_configure'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/supervisor.rb:581:in `dry_run'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/supervisor.rb:599:in `supervise'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/supervisor.rb:504:in `run_supervisor'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/command/fluentd.rb:314:in `<top (required)>'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/bin/fluentd:8:in `<top (required)>'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/bin/fluentd:23:in `load'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /opt/google-fluentd/embedded/bin/fluentd:23:in `<top (required)>'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /usr/sbin/google-fluentd:7:in `load'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:         from /usr/sbin/google-fluentd:7:in `<main>'
Nov 29 09:54:10 ip-172-31-39-186 google-fluentd[20655]:  * google-fluentd
Nov 29 09:54:10 ip-172-31-39-186 systemd[1]: google-fluentd.service: Control process exited, code=exited status=1
Nov 29 09:54:10 ip-172-31-39-186 systemd[1]: google-fluentd.service: Failed with result 'exit-code'.
Nov 29 09:54:10 ip-172-31-39-186 systemd[1]: Failed to start LSB: data collector for Treasure Data.
-- Subject: Unit google-fluentd.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit google-fluentd.service has failed.
-- 
-- The result is RESULT.
Nov 29 09:54:10 ip-172-31-39-186 ubuntu[20691]: Test syslog message from google-fluentd-1.6.25-1 at Fri Nov 29 09:54:10 UTC 2019.
Nov 29 09:54:10 ip-172-31-39-186 sudo[20142]: pam_unix(sudo:session): session closed for user root
Nov 29 09:54:58 ip-172-31-39-186 sudo[20711]:   ubuntu : TTY=pts/2 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/bin/journalctl -xe
Nov 29 09:54:58 ip-172-31-39-186 sudo[20711]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Nov 29 09:55:06 ip-172-31-39-186 sudo[20711]: pam_unix(sudo:session): session closed for user root
Nov 29 09:55:48 ip-172-31-39-186 sudo[20723]:   ubuntu : TTY=pts/2 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/bin/journalctl -xe
Nov 29 09:55:48 ip-172-31-39-186 sudo[20723]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Nov 29 09:55:50 ip-172-31-39-186 sudo[20723]: pam_unix(sudo:session): session closed for user root
Nov 29 09:57:06 ip-172-31-39-186 sudo[20735]:   ubuntu : TTY=pts/2 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/bin/journalctl -xe
Nov 29 09:57:06 ip-172-31-39-186 sudo[20735]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Nov 29 09:57:34 ip-172-31-39-186 sudo[20735]: pam_unix(sudo:session): session closed for user root
Nov 29 09:57:53 ip-172-31-39-186 sudo[20747]:   ubuntu : TTY=pts/2 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/bin/journalctl -xe
Nov 29 09:57:53 ip-172-31-39-186 sudo[20747]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
lines 1295-1361/1361 (END)
```

**Comment by chetan-happyness** [comment]
@igorpeshansky , thanks for your response. I was able to fix the installation issue after adding the credential file (application_default_credentials.json).

**Comment by igorpeshansky** [comment]
Great, I'm glad the full exception message helped resolve this.
