### ISSUE TITLE
Warning "this cannot include CR/LF"

### ISSUE THREAD

**Issue by sneko** [GoogleCloudPlatform/fluent-plugin-google-cloud#364]
Hi,

I just upgraded the operator to 1.11.0 and I get those warnings
```
2020-01-09 13:04:05 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="header User-Agent has field value \"Fluentd Google Cloud Logging plugin/0.4.10 google-api-ruby-client/0.8.7 Linux/4.4.64+\\n (gzip)\", this cannot include CR/LF"
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http/header.rb:23:in `block in initialize_http_header'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http/header.rb:16:in `each'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http/header.rb:16:in `initialize_http_header'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http/generic_request.rb:46:in `initialize'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:67:in `new'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:67:in `create_request'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:87:in `perform_request'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:43:in `block in call'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:38:in `call'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/response.rb:8:in `call'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/google-api-client-0.8.7/lib/google/api_client/request.rb:163:in `send'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/google-api-client-0.8.7/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/google-api-client-0.8.7/lib/google/api_client.rb:645:in `block in execute!'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/google-api-client-0.8.7/lib/google/api_client.rb:636:in `execute!'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-google-cloud-0.4.10/lib/fluent/plugin/out_google_cloud.rb:459:in `block in write'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-google-cloud-0.4.10/lib/fluent/plugin/out_google_cloud.rb:294:in `each'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-google-cloud-0.4.10/lib/fluent/plugin/out_google_cloud.rb:294:in `write'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/compat/output.rb:131:in `write'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2020-01-09 13:04:05 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-01-09 13:04:05 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3ffa4f5ecd54/59bb4a10840d5bc01d5642b643adc885.log
```

Do you know what could be the origin? It seems indeed a `\n` char is in the User-Agent, but no one else seems to have that.

Thank you,

Note: I have this kind of settings:
```
<match **>
  @type google_cloud
  use_grpc true
</match>
```

**Comment by igorpeshansky** [comment]
Looking at the version string (`Fluentd Google Cloud Logging plugin/0.4.10`), 0.4.10 is ancient (from back in 2015). That would be the first issue to fix.

I don't know what operator you're using, but a bit more detail about your environment would be helpful.

Note that version 0.4.10 also didn't support grpc yet, as evidenced by the "google-api-ruby-client" in the version string.

**Comment by sneko** [comment]
Oh my bad... I'm using the VMware operator and you're right. In their README.md (https://github.com/vmware/kube-fluentd-operator) they indeed precise the `fluent-plugin-google-cloud` version at 0.4.10

Weird no one mentioned that before! I will ask them to update or patch it manually.

Thank you,

**Comment by sneko** [comment]
Hi @igorpeshansky , I succeeded in patching the image (not easy I got into other troubles...). I'm noticing all logs with the `stream` property have it set to `stderr` even for logs content equal to TRACE/DEBUG/INFO.

Do you know if there is something special to configure? That's strange 🤔

**Comment by sneko** [comment]
@igorpeshansky please find some information from the maintainer of the operator what is blocking from `fluent-plugin-google-cloud` dependency requirements https://github.com/vmware/kube-fluentd-operator/issues/96#issuecomment-573110253
