### ISSUE TITLE
Runtime issue protobuf_c.so: __va_copy: symbol not found

### ISSUE THREAD

**Issue by MrVentzi** [GoogleCloudPlatform/fluent-plugin-google-cloud#419]
I've installed the latest version.

Gemfile:
```
gem "fluentd", "1.7.4"
gem "oj", "3.8.1"
gem "fluent-plugin-multi-format-parser", "~> 1.0.0"
gem "fluent-plugin-concat", "~> 2.3.0"
gem "fluent-plugin-grok-parser", "~> 2.5.0"
gem "fluent-plugin-prometheus", "~> 1.5.0"
gem 'fluent-plugin-json-in-json-2', ">= 1.0.2"
gem "fluent-plugin-record-modifier", "~> 2.0.0"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.2.0"
gem "fluent-plugin-google-cloud", "0.9.1"
gem "fluent-plugin-gcs", "0.4.0"
gem "fluent-plugin-kubernetes_metadata_filter", "~> 2.3.0"
gem "ffi"
gem "json", "2.2.0"
gem "bigdecimal", "1.4.4"
```

Dockerfile:
```
FROM fluent/fluentd:v1.7.4-1.0

USER root
WORKDIR /home/fluent
ENV PATH /fluentd/vendor/bundle/ruby/2.6.0/bin:$PATH
ENV GEM_PATH /fluentd/vendor/bundle/ruby/2.6.0
ENV GEM_HOME /fluentd/vendor/bundle/ruby/2.6.0

ENV FLUENTD_DISABLE_BUNDLER_INJECTION 1

COPY Gemfile* /fluentd/
RUN set -ex \
    && apk upgrade --no-cache \
    && apk add --no-cache ruby-bundler \
    && apk add --no-cache --virtual .build-deps \
        build-base \
        ruby-dev \
        libffi-dev \
    && gem install bundler --version 2.0.1 \
    && bundle config silence_root_warning true \
    && bundle install --gemfile=/fluentd/Gemfile \
    && apk del .build-deps \
    && gem sources --clear-all \
    && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

# Copy configuration files
COPY ./conf/fluent.conf /fluentd/etc/
#RUN touch /fluentd/etc/disable.conf

# Copy plugins
COPY plugins /fluentd/plugins/
COPY entrypoint.sh /fluentd/entrypoint.sh

# Environment variables
ENV FLUENTD_OPT=""
ENV FLUENTD_CONF="fluent.conf"

RUN chmod 755 /fluentd/entrypoint.sh
# Overwrite ENTRYPOINT to run fluentd as root for /var/log / /var/lib
ENTRYPOINT ["tini", "--", "/fluentd/entrypoint.sh"]
```

Getting this on runtime

```
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': Error relocating /fluentd/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.12.2/lib/google/protobuf_c.so: __va_copy: symbol not found - /fluentd/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.12.2/lib/google/protobuf_c.so (LoadError)
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.12.2/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.12.2/lib/google/protobuf.rb:48:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.12.2/lib/google/protobuf/any_pb.rb:4:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.12.2/lib/google/protobuf/well_known_types.rb:32:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-gax-1.8.1/lib/google/gax/grpc.rb:34:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-gax-1.8.1/lib/google/gax/errors.rb:32:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-gax-1.8.1/lib/google/gax/api_callable.rb:32:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-gax-1.8.1/lib/google/gax.rb:30:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-1.6.6/lib/google/cloud/logging/v2/config_service_v2_client.rb:26:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-1.6.6/lib/google/cloud/logging/v2.rb:16:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-google-cloud-0.9.1/lib/fluent/plugin/out_google_cloud.rb:24:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:102:in `block in search'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:99:in `each'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:99:in `search'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:44:in `lookup'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/plugin.rb:146:in `new_impl'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/plugin.rb:104:in `new_output'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/agent.rb:128:in `add_match'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/agent.rb:72:in `block in configure'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/agent.rb:64:in `each'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/agent.rb:64:in `configure'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:150:in `configure'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/engine.rb:131:in `configure'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/engine.rb:96:in `run_configure'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:812:in `run_configure'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:589:in `dry_run'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:607:in `supervise'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:512:in `run_supervisor'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/command/fluentd.rb:324:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/bin/fluentd:8:in `<top (required)>'
        from /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
        from /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
```

I am only doing as a test
 ```
   <match **>
      @type google_cloud
    </match>
```

Any ideas?

**Comment by igorpeshansky** [comment]
Don't use the `fluent/fluentd:v1.7.4-1.0` base image. It's based off Alpine, and Alpine is known to have such issues, e.g.: https://github.com/protocolbuffers/protobuf/issues/2335. This specific error may have been fixed in [Alpine 3.11.5](https://alpinelinux.org/posts/Alpine-3.11.5-released.html), but `fluent/fluentd:v1.7.4-1.0` [uses Alpine 3.9](https://github.com/fluent/fluentd-docker-image/blob/master/v1.7/alpine/Dockerfile) (even `v1.11.2-1.0` still uses 3.9).

As a side note, this plugin was designed to work as part of the [`google-fluentd`](https://github.com/GoogleCloudPlatform/google-fluentd) package, and the use case of a standalone plugin is not officially supported. That said, it should work if you use `fluent/fluentd:v1.7.4-debian-2.0` as your base.
