### ISSUE TITLE
NoMethodError happened while using the plugin

### ISSUE THREAD

**Issue by maxlee0782r** [GoogleCloudPlatform/fluent-plugin-google-cloud#425]
I'm facing a problem using the plugin. I'm running Fluentd in Debian:stretch docker image(Debian GNU/Linux 9) with the plugin.
I used the default Fluentd config and just adding some lines as below.

```
<filter test.**>
  @type add_insert_ids
  insert_id_key my_insert_id_field_name # Optional.
  @log_level debug
</filter>

<match test.**>
  @type google_cloud
  @log_level debug
</match>
```

The plugin version is 0.10.1 and install from gem. 
And the error stacktrace is as below.

```
2020-09-01 08:13:15 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `each' for nil:NilClass"
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:48:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:47:in `tap'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:47:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:18:in `evaluate'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:10:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `each'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `inject'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/binding.rb:32:in `compile_fragment'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:53:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:51:in `each'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:51:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:70:in `representable_map!'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:45:in `create_representation_with'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/hash.rb:34:in `to_hash'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/serializer.rb:44:in `block in <module:Representable>'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:18:in `evaluate'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:10:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `each'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `inject'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/binding.rb:32:in `compile_fragment'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:53:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:51:in `each'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:51:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:70:in `representable_map!'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:45:in `create_representation_with'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/hash.rb:34:in `to_hash'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/serializer.rb:44:in `block in <module:Representable>'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:18:in `evaluate'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:10:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `each'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `inject'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:39:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:38:in `each'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:38:in `each_with_index'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:38:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:18:in `evaluate'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:10:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `each'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `inject'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/binding.rb:32:in `compile_fragment'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:53:in `block in call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:51:in `each'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:51:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:70:in `representable_map!'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable.rb:45:in `create_representation_with'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/hash.rb:34:in `to_hash'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/representable-3.0.4/lib/representable/json.rb:44:in `to_json'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.30.8/lib/google/apis/core/api_command.rb:64:in `prepare!'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.30.8/lib/google/apis/core/http_command.rb:99:in `execute'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.30.8/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.30.8/generated/google/apis/logging_v2/service.rb:695:in `write_entry_log_entries'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-google-cloud-0.10.1/lib/fluent/plugin/out_google_cloud.rb:970:in `write_request_via_rest'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-google-cloud-0.10.1/lib/fluent/plugin/out_google_cloud.rb:758:in `call'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-google-cloud-0.10.1/lib/fluent/plugin/out_google_cloud.rb:758:in `write'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.2/lib/fluent/compat/output.rb:131:in `write'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-09-01 08:13:15 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

Gem packages

```
addressable (2.7.0)
async (1.24.2)
async-http (0.50.8)
async-io (1.27.7)
async-pool (0.2.0)
aws-eventstream (1.1.0)
aws-partitions (1.297.0)
aws-sdk-core (3.94.0)
aws-sdk-kms (1.30.0)
aws-sdk-s3 (1.63.0)
aws-sdk-sqs (1.24.0)
aws-sigv4 (1.1.1)
bigdecimal (default: 1.3.2)
bundler (1.16.6)
concurrent-ruby (1.1.6)
console (1.8.2)
cool.io (1.6.0)
declarative (0.0.20)
declarative-option (0.1.0)
did_you_mean (1.1.0)
digest-crc (0.5.1)
elasticsearch (6.8.1)
elasticsearch-api (6.8.1)
elasticsearch-transport (6.8.1)
excon (0.73.0)
faraday (0.17.3)
ffi (1.12.2)
fluent-config-regexp-type (1.0.0)
fluent-logger (0.8.2)
fluent-plugin-elasticsearch (4.0.7)
fluent-plugin-google-cloud (0.10.1)
fluent-plugin-kafka (0.13.0)
fluent-plugin-prometheus (1.7.3)
fluent-plugin-prometheus_pushgateway (0.0.2)
fluent-plugin-record-modifier (2.1.0)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-s3 (1.3.1)
fluent-plugin-systemd (1.0.2)
fluent-plugin-td (1.1.0)
fluent-plugin-td-monitoring (0.2.4)
fluent-plugin-webhdfs (1.2.4)
fluentd (1.11.2, 1.10.2)
gapic-common (0.3.4)
google-api-client (0.30.8)
google-cloud-core (1.5.0)
google-cloud-env (1.3.3)
google-cloud-errors (1.0.1)
google-cloud-logging (1.6.6)
google-cloud-monitoring (0.38.0)
google-cloud-trace (0.40.0)
google-cloud-trace-v1 (0.1.2)
google-cloud-trace-v2 (0.1.2)
google-gax (1.8.1)
google-protobuf (3.12.2 x86_64-linux)
googleapis-common-protos (1.3.9)
googleapis-common-protos-types (1.0.5)
googleauth (0.9.0)
grpc (1.31.1 x86_64-linux)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jmespath (1.4.0)
json (2.2.0, default: 2.0.4)
jwt (2.2.2)
ltsv (0.1.2)
memoist (0.16.2)
mini_mime (1.0.2)
mini_portile2 (2.4.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
msgpack (1.3.3)
multi_json (1.14.1)
multipart-post (2.1.1)
net-telnet (0.1.1)
nio4r (2.5.2)
nokogiri (1.10.9)
ohai (6.20.0)
oj (3.8.1)
opencensus (0.5.0)
opencensus-stackdriver (0.3.2)
openssl (default: 2.0.9)
os (1.1.1)
parallel (1.19.1)
power_assert (0.4.1)
prometheus-client (0.9.0)
protocol-hpack (1.4.2)
protocol-http (0.15.1)
protocol-http1 (0.10.3)
protocol-http2 (0.11.6)
psych (default: 2.2.2)
public_suffix (4.0.4)
quantile (0.2.1)
rake (12.3.3, 12.0.0)
rdkafka (0.7.0)
rdoc (default: 5.0.1)
representable (3.0.4)
retriable (3.1.2)
rly (0.2.3)
ruby-kafka (1.0.0)
ruby-progressbar (1.10.1)
rubyzip (1.3.0)
serverengine (2.2.1)
sigdump (0.2.4)
signet (0.14.0)
stackdriver-core (1.4.0)
strptime (0.2.3)
systemd-journal (1.3.3)
systemu (2.5.2)
td (0.16.8)
td-client (1.0.7)
td-logger (0.3.27)
test-unit (3.2.3)
timers (4.3.0)
tzinfo (2.0.2)
tzinfo-data (1.2019.3)
uber (0.1.0)
webhdfs (0.9.0)
xmlrpc (0.2.1)
yajl-ruby (1.4.1)
zip-zip (0.3)
```

**Comment by igorpeshansky** [comment]
This is very likely a problem with your inputs — some field of the input record (probably the timestamp) is `nil`. Do you get this error consistently? Does it also occur if you set up a different output plugin (e.g., `@type stdout` with `output_type json` and `include_time_key`/`include_tag_key` set to `true`)?

**Comment by maxlee0782r** [comment]
I tried both tail and http input source and the error still happened.
Following is my whole fluentd config, I didn't set any timestamp key. 
And I send the `curl -X POST -d 'json={"msg":"hello world"}' http://localhost:8888/testlog.log`, there is the error.
```
<source>
  @type http
  @id input_http
  port 8888
</source>

<source>
  @type tail
  format none 
  path /var/log/test.log
  pos_file /tmp/testlog.pos
  read_from_head true
  tag testlog
</source>

<match testlog>
  @type google_cloud
</match>

<filter testlog>
  @type add_insert_ids
</filter>

```

**Comment by igorpeshansky** [comment]
Have you tried this with a different _output_ plugin? Can you also try enabling the gRPC (`use_grpc true` in the `google_cloud` plugin config) to see if you get a different error?

Since we suspect the timestamp being nil, can you also try to set the timestamp in the URL parameters when sending the message, as documented in https://docs.fluentd.org/input/http#basic-usage?

**Comment by maxlee0782r** [comment]
I turned to use google-fluentd which works, close this issue

**Comment by aliabbasrizvi** [comment]
@maxlee0782r I am running into the same issue and I followed your suggestion here to use `google-fluentd`. Were there other filters you were applying to get this to work with `google_cloud`? Was your final config similar to what you shared above or did you have to change it to make it work?

**Comment by igorpeshansky** [comment]
@maxlee0782r Ah. Yes, the `google-fluentd` package was designed to work with the `google_cloud` output plugin. I should have picked up on you using the raw `td-agent` package before.

@aliabbasrizvi Are you seeing this error with the `google-fluentd` package? Are you in a position to open a Cloud Support issue? That would make it a lot easier to investigate, and will provide much better tracking on your side.

**Comment by aliabbasrizvi** [comment]
@igorpeshansky we ended up using fluent bit based on the suggestion [here](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/473)
