### ISSUE TITLE
NoMethodError: undefined method each

### ISSUE THREAD

**Issue by aliabbasrizvi** [GoogleCloudPlatform/fluent-plugin-google-cloud#473]
I am setting up the plugin starting with the base image: https://hub.docker.com/r/fluent/fluentd v1.13-1

```
fluentd_1     | 2021-09-02 17:01:34 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd_1     | 2021-09-02 17:01:34 +0000 [info]: gem 'fluent-plugin-google-cloud' version '0.12.0'
fluentd_1     | 2021-09-02 17:01:34 +0000 [info]: gem 'fluentd' version '1.13.3'
fluentd_1     | 2021-09-02 17:01:34 +0000 [info]: use_metadata_service is false; not detecting platform
fluentd_1     | 2021-09-02 17:01:34 +0000 [info]: use_metadata_service is false; not detecting platform
fluentd_1     | 2021-09-02 17:01:34 +0000 [info]: using configuration file: <ROOT>
fluentd_1     |   <source>
fluentd_1     |     @type forward
fluentd_1     |   </source>
fluentd_1     |   <filter **>
fluentd_1     |     @type add_insert_ids
fluentd_1     |   </filter>
fluentd_1     |   <label @FLUENT_LOG>
fluentd_1     |     <match fluent.*>
fluentd_1     |       @type google_cloud
fluentd_1     |       use_metadata_service false
fluentd_1     |       <format>
fluentd_1     |         @type stdout
fluentd_1     |         output_type json
fluentd_1     |       </format>
fluentd_1     |       <buffer>
fluentd_1     |         flush_mode interval
fluentd_1     |         retry_type exponential_backoff
fluentd_1     |       </buffer>
fluentd_1     |     </match>
fluentd_1     |   </label>
fluentd_1     |   <match my_service>
fluentd_1     |     @type google_cloud
fluentd_1     |     use_metadata_service false
fluentd_1     |     <buffer>
fluentd_1     |       flush_mode interval
fluentd_1     |       retry_type exponential_backoff
fluentd_1     |     </buffer>
fluentd_1     |   </match>
fluentd_1     | </ROOT>
fluentd_1     | 2021-09-02 17:01:34 +0000 [info]: starting fluentd-1.13.3 pid=7 ruby="2.7.4"
fluentd_1     | 2021-09-02 17:01:34 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "--config", "/fluentd/etc/fluent.conf", "--plugin", "/fluentd/plugins", "--under-supervisor"]
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: adding match in @FLUENT_LOG pattern="fluent.*" type="google_cloud"
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: #0 use_metadata_service is false; not detecting platform
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: adding filter pattern="**" type="add_insert_ids"
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: adding match pattern="hocuspocus" type="google_cloud"
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: #0 use_metadata_service is false; not detecting platform
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: adding source type="forward"
fluentd_1     | 2021-09-02 17:01:35 +0000 [warn]: section <format> is not used in <match fluent.*> of google_cloud plugin
fluentd_1     | 2021-09-02 17:01:35 +0000 [warn]: section <format> is not used in <match fluent.*> of google_cloud plugin
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: #0 starting fluentd worker pid=17 ppid=7 worker=0
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: #0 Started the add_insert_ids plugin with logging.googleapis.com/insertId as the insert ID key.
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: #0 Initialized the insert ID key to 283jzfcfg0etalgnt.
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
fluentd_1     | 2021-09-02 17:01:35 +0000 [info]: #0 fluentd worker is now running worker=0
fluentd_1     | 2021-09-02 17:02:36 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `each' for nil:NilClass"
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:49:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:48:in `tap'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:48:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:19:in `evaluate'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:10:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `each'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `inject'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:50:in `compile_fragment'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:14:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `each'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable.rb:68:in `representable_map!'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable.rb:56:in `create_representation_with'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/hash.rb:37:in `to_hash'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/serializer.rb:45:in `block in <module:Representable>'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:19:in `evaluate'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:10:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `each'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `inject'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:50:in `compile_fragment'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:14:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `each'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable.rb:68:in `representable_map!'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable.rb:56:in `create_representation_with'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/hash.rb:37:in `to_hash'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/serializer.rb:45:in `block in <module:Representable>'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:19:in `evaluate'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:10:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `each'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `inject'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:40:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:39:in `each'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:39:in `each_with_index'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:39:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:19:in `evaluate'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:10:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `each'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `inject'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:50:in `compile_fragment'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:14:in `block in call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `each'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable.rb:68:in `representable_map!'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable.rb:56:in `create_representation_with'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/hash.rb:37:in `to_hash'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/representable-3.1.1/lib/representable/json.rb:42:in `to_json'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/google-api-client-0.30.8/lib/google/apis/core/api_command.rb:64:in `prepare!'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/google-api-client-0.30.8/lib/google/apis/core/http_command.rb:99:in `execute'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/google-api-client-0.30.8/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/google-api-client-0.30.8/generated/google/apis/logging_v2/service.rb:695:in `write_entry_log_entries'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-google-cloud-0.12.0/lib/fluent/plugin/out_google_cloud.rb:1013:in `write_request_via_rest'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-google-cloud-0.12.0/lib/fluent/plugin/out_google_cloud.rb:789:in `call'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-google-cloud-0.12.0/lib/fluent/plugin/out_google_cloud.rb:789:in `write'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/compat/output.rb:131:in `write'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1138:in `try_flush'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1450:in `flush_thread_run'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
fluentd_1     |   2021-09-02 17:02:36 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
fluentd_1     | 2021-09-02 17:02:36 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_5a78/5cb0622b1bb6c59b2d16b76faba6e068.log
```

When I use `@type stdout` it works perfectly well. I have set up the credentials correctly in a credentials file and set `GOOGLE_APPLICATION_CREDENTIALS` env variable.

Any hint on what could be going wrong? Any tips will be helpful.

Thanks

**Comment by arsenyspb** [comment]
Hi @aliabbasrizvi the fluentd and the approach with the plugin for integration is under "Legacy" section in the documentation. 

I'd strongly encourage you to collect telemetry data for Cloud Operations using the primary way, which is [OpsAgent](https://cloud.google.com/logging/docs/agent/ops-agent) based on [Fluentbit](https://fluentbit.io/)

**Comment by aliabbasrizvi** [comment]
@arsenyspb thanks for getting back on this. Let me check that out.

**Comment by aliabbasrizvi** [comment]
@arsenyspb using Fluentbit worked well for me. Closing this as resolved.

**Comment by polyamide** [comment]
I have some more information for people who stumble upon this issue.

1. Adding `use_grpc true` to your fluentd config can avoid this problem. The error seems only happen when it try to serialize request body for restful API. Document states that `use_grpc`'s default value is `true` seems to be incorrect. According to this line: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/39e48e8add1bafa5c14f0199713c6416d3d399ec/lib/fluent/plugin/out_google_cloud.rb#L321

2. At `/usr/lib/ruby/gems/2.7.0/gems/google-api-client-0.30.8/lib/google/apis/core/api_command.rb:64:in `prepare!'`, I dump the variable `request_object`, and got following result: (truncated for brevity)

```
#<Google::Apis::LoggingV2::WriteLogEntriesRequest:0x00005561280c93e0
  @entries=[
    #<Google::Apis::LoggingV2::LogEntry:0x000055612879bab0
      @labels={"compute.googleapis.com/resource_name"=>"41dd808ef983"},
      @resource=#<Google::Apis::LoggingV2::MonitoredResource:0x00005561286f41c0
        @labels=nil,
        @type="gce_instance"
      >, 
      @severity="DEFAULT",
      @timestamp={:seconds=>1636084536, :nanos=>471760550},
      @json_payload={"test"=>1234},
      @log_name="projects/kkbox-log-testing/logs/kkbox.johntest"
    >,
```

I am not familiar with Ruby nor this library, but that `@labels=nil` maybe have something to do with this problem.
